import colorPhone from "./colorPhone";
import infoPhones from "./infoPhone";

const phonesApi = [
  {
    _id: "67rdca3eeb7f6fgeed471815",
    brand: "Sony Ericsson",
    name: "XPERIA X10",
    type: "smartphone",
    typeDisplay: "sensor",
    date: 2009,
    accumulator: 1500,
    weight: 135,
    rate: 9.4,
    price: 455,
    count: 3,
    color: [colorPhone.black, colorPhone.white],
    best: "false",
    info: infoPhones.x10,
  },
  {
    _id: "67rdca3eeb7f6fgeed471816",
    brand: "Sony Ericsson",
    name: "W995",
    type: "slider",
    typeDisplay: "TFT",
    date: 2009,
    accumulator: 1350,
    weight: 113,
    rate: 9.5,
    price: 380,
    count: 2,
    color: [colorPhone.black, colorPhone.silver, colorPhone.red],
    best: "false",
    info: infoPhones.w995,
  },
  {
    _id: "67rdca3eeb7f6fgeed471817",
    brand: "Sony Ericsson",
    name: "K750i",
    type: "phone",
    typeDisplay: "TFT",
    date: 2005,
    accumulator: 900,
    weight: 99,
    rate: 9,
    price: 270,
    count: 11,
    color: [colorPhone.black, colorPhone.silver],
    best: "true",
    info: infoPhones.k750i,
  },
  {
    _id: "67rdca3eeb7f6fgeed471818",
    brand: "Sony Ericsson",
    name: "K700i",
    type: "phone",
    typeDisplay: "TFT",
    date: 2004,
    accumulator: 700,
    weight: 93,
    rate: 8.5,
    price: 210,
    count: 5,
    color: [colorPhone.white, colorPhone.silver],
    best: "false",
    info: infoPhones.k700i,
  },
  {
    _id: "67rdca3eeb7f6fgeed471819",
    brand: "Sony Ericsson",
    name: "T270i",
    type: "phone",
    typeDisplay: "TFT",
    date: 2008,
    accumulator: 780,
    weight: 82,
    rate: 6.2,
    price: 75,
    count: 34,
    color: [colorPhone.black, colorPhone.silver],
    best: "false",
    info: infoPhones.k700i,
  },
  {
    _id: "67rdca3eeb7f6fgeed471814f3",
    brand: "Sony Ericsson",
    name: "W600i",
    type: "rotator",
    typeDisplay: "TFT",
    date: 2005,
    accumulator: 820,
    weight: 120,
    rate: 8.2,
    price: 220,
    count: 4,
    color: [colorPhone.orange],
    best: "false",
    info: infoPhones.w600,
  },
  {
    _id: "67rdca3eeb7f6fgeed471814b3",
    brand: "Sony Ericsson",
    name: "W710i",
    type: "flip",
    typeDisplay: "TFT",
    date: 2006,
    accumulator: 900,
    weight: 101,
    rate: 8.8,
    price: 310,
    count: 7,
    color: [colorPhone.silver, colorPhone.orange],
    best: "true",
    info: infoPhones.w710,
  },
  {
    _id: "67rdca3eeb7f6fgeed471814j3",
    brand: "Sony Ericsson",
    name: "W980",
    type: "flip",
    typeDisplay: "TFT",
    date: 2008,
    accumulator: 890,
    weight: 100,
    rate: 8.8,
    price: 300,
    count: 1,
    color: [colorPhone.black],
    best: "false",
    info: infoPhones.w600,
  },
  {
    _id: "67rdca3eeb7f6fgeed471820",
    brand: "Nokia",
    name: "5800 XpressMusic",
    type: "smartphone",
    typeDisplay: "sensor",
    date: 2008,
    accumulator: 1320,
    weight: 109,
    rate: 9.4,
    price: 400,
    count: 11,
    color: [colorPhone.black],
    best: "true",
    info: infoPhones.x5800,
  },
  {
    _id: "67rdca3eeb7f6fgeed471821",
    brand: "Nokia",
    name: "6300",
    type: "phone",
    typeDisplay: "TFT",
    date: 2006,
    accumulator: 860,
    weight: 91,
    rate: 9.1,
    price: 190,
    count: 6,
    color: [colorPhone.black, colorPhone.silver, colorPhone.red],
    best: "true",
    info: infoPhones.n6300,
  },
  {
    _id: "67rdca3eeb7f6fgeed471822",
    brand: "Nokia",
    name: "7610",
    type: "smartphone",
    typeDisplay: "TFT",
    date: 2004,
    accumulator: 900,
    weight: 118,
    rate: 8.9,
    price: 285,
    count: 2,
    color: [colorPhone.black, colorPhone.silver],
    best: "true",
    info: infoPhones.n6300,
  },
  {
    _id: "67rdca3eeb7f6fgeed471823",
    brand: "Nokia",
    name: "N90",
    type: "smartphone",
    typeDisplay: "TFT",
    date: 2005,
    accumulator: 760,
    weight: 173,
    rate: 8.4,
    price: 335,
    count: 1,
    color: [colorPhone.silver],
    best: "false",
    info: infoPhones.n90,
  },
  {
    _id: "67rdca3eeb7f6fgeed471824",
    brand: "Nokia",
    name: "7373",
    type: "rotator",
    typeDisplay: "TFT",
    date: 2006,
    accumulator: 700,
    weight: 104,
    rate: 9.2,
    price: 300,
    count: 2,
    color: [colorPhone.pink, colorPhone.black],
    best: "false",
    info: infoPhones.n7373,
  },
  {
    _id: "67rdca3eeb7f6fgeed47181f",
    brand: "Nokia",
    name: "6131",
    type: "flip",
    typeDisplay: "TFT",
    date: 2006,
    accumulator: 820,
    weight: 102,
    rate: 9.2,
    price: 120,
    count: 2,
    color: [colorPhone.black, colorPhone.white, colorPhone.red, colorPhone.brown],
    best: "false",
    info: infoPhones.n6131,
  },
  {
    _id: "67rdca3eeb7f6fgeed47181r",
    brand: "Nokia",
    name: "Nokia 5610 XpressMusic",
    type: "slider",
    typeDisplay: "TFT",
    date: 2007,
    accumulator: 900,
    weight: 111,
    rate: 9.2,
    price: 270,
    count: 7,
    color: [colorPhone.blue, colorPhone.red],
    best: "false",
    info: infoPhones.n5610,
  },
  {
    _id: "67rdca3eeb7f6fgeed47181rm1",
    brand: "Motorola",
    name: "MPx200",
    type: "smartphone",
    typeDisplay: "TFT",
    date: 2003,
    accumulator: 860,
    weight: 118,
    rate: 8.8,
    price: 240,
    count: 2,
    color: [colorPhone.black],
    best: "false",
    info: infoPhones.mpx200,
  },
  {
    _id: "67rdca3eeb7f6fgeed47181rm2",
    brand: "Motorola",
    name: "RIZR Z3",
    type: "slider",
    typeDisplay: "TFT",
    date: 2006,
    accumulator: 720,
    weight: 115,
    rate: 8.4,
    price: 160,
    count: 6,
    color: [colorPhone.black, colorPhone.blue, colorPhone.red],
    best: "false",
    info: infoPhones.z3,
  },
  {
    _id: "67rdca3eeb7f6fgeed47181rm3",
    brand: "Motorola",
    name: "Aura",
    type: "rotator",
    typeDisplay: "TFT",
    date: 2008,
    accumulator: 810,
    weight: 141,
    rate: 7.3,
    price: 2000,
    count: 1,
    color: [colorPhone.silver],
    best: "false",
    info: infoPhones.aura,
  },
  {
    _id: "67rdca3eeb7f6fgeed47181rm4",
    brand: "Motorola",
    name: "RAZR V3",
    type: "flip",
    typeDisplay: "TFT",
    date: 2004,
    accumulator: 680,
    weight: 95,
    rate: 8.1,
    price: 150,
    count: 19,
    color: [colorPhone.pink, colorPhone.black, colorPhone.silver],
    best: "true",
    info: infoPhones.v3,
  },
  {
    _id: "67rdca3eeb7f6fgeed47181rm5",
    brand: "Motorola",
    name: "E398",
    type: "phone",
    typeDisplay: "TFT",
    date: 2004,
    accumulator: 830,
    weight: 108,
    rate: 6.9,
    price: 175,
    count: 22,
    color: [colorPhone.black],
    best: "true",
    info: infoPhones.e398,
  },
  {
    _id: "67rdca3eeb7f6fgeed47181rm6",
    brand: "Motorola",
    name: "SLVR L7e",
    type: "phone",
    typeDisplay: "TFT",
    date: 2006,
    accumulator: 820,
    weight: 96,
    rate: 8.9,
    price: 210,
    count: 9,
    color: [colorPhone.blue],
    best: "false",
    info: infoPhones.L7e,
  },
];

export default phonesApi;
